### ISSUE TITLE
Lembrar de documentar no README.md

### ISSUE THREAD

**Issue by armando-couto** [jhoonnyy1812/TorreHanoiSeuEstagio#1]
O que é preciso:
- Como roda;
- Qual versão da linguagem.
- O que é esse programa.

**Comment by jhoonnyy1812** [comment]
Corrigido, já foi atualizado online.

Em qua., 8 de abr. de 2020 às 00:07, Antonio Armando Couto Bem Filho <
notifications@github.com> escreveu:
